--root - Intento1

CREATE USER 'omar_h'@'%' IDENTIFIED BY 'marsupial';

GRANT ALL PRIVILEGES ON *.* TO 'omar_h'@'%' WITH GRANT OPTION;


CREATE DATABASE OBRAS_CONTROL; 
USE OBRAS_CONTROL; 

CREATE USER 'TAMAWEB'@'localhost' IDENTIFIED BY 'Intento2';

GRANT ALL PRIVILEGES ON OBRAS_CONTROL.* TO 'TAMAWEB'@'localhost';

CREATE TABLE IF NOT EXISTS VEHICULO (
    VEHICULO_ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255),
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    COLOR VARCHAR(255),
    MATRICULA VARCHAR(255),
    ANIO INT,
    ESTATUS INT DEFAULT 1,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (VEHICULO_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PERSONA (
    PERSONA_ID INT AUTO_INCREMENT,
    TIPO_PERSONA INT,
    NOMBRE VARCHAR(255),
    APELLIDOS VARCHAR(255),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(255),
    EMAIL VARCHAR(255),
    NOMBRE_EMPRESA VARCHAR(255),
    NUMERO_EMPLEADO VARCHAR(255),
    FECHA_NACIMIENTO DATE,
    EDAD INT,
    RFC VARCHAR(255),
    ESTATUS INT DEFAULT 1,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (PERSONA_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS OBRA (
    OBRA_ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    DIRECCION VARCHAR(255),
    CLIENTE_ID INT,
    FECHA_FIN DATE,
    ESTATUS INT DEFAULT 1,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (OBRA_ID),
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES PERSONA(PERSONA_ID)
    ON DELETE CASCADE
)  
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS REVOLVENTE (
    REVOLVENTE_ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(255),
    ES_INGRESO TINYINT(1),
    MONTO FLOAT(16,2),
    OBRA_ID INT,
    VEHICULO_ID INT,
    CANTIDAD INT,	
    ESTATUS INT DEFAULT 1,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (REVOLVENTE_ID),
    FOREIGN KEY (OBRA_ID)
    REFERENCES OBRA(OBRA_ID)
    ON DELETE CASCADE
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS INVENTARIO (
    INVENTARIO_ID INT AUTO_INCREMENT,
    CANTIDAD INT,
    DESCRIPCION VARCHAR(255),
    EN_RENTA INT DEFAULT 0,
    PRECIO_UNITARIO FLOAT(16,2),
    TOTAL FLOAT(16,2),
    ESTATUS INT DEFAULT 1,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (INVENTARIO_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS RENTA (
    RENTA_ID INT AUTO_INCREMENT,
    EMPLEADO_ID INT ,
    DESCRIPCION VARCHAR(255),
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_INICIO DATE,
    FECHA_FINAL DATE,
    ESTATUS INT DEFAULT 1,
    PRIMARY KEY (RENTA_ID)
)  ENGINE=INNODB;




INSERT INTO PERSONA (TIPO_PERSONA,NOMBRE,APELLIDOS,DIRECCION,TELEFONO,FECHA_NACIMIENTO,EDAD,RFC,NOMBRE_EMPRESA) VALUES ('1','Jorge Alberto','López Herrera','La gloria 16','5581738739','1989-04-13',29,'LOHJ890413629','BANAMEX');
INSERT INTO OBRA (NOMBRE,DIRECCION,CLIENTE_ID) VALUES ('OBRA EN ACORAZ','OTRA Av. Reforma 222' ,'1' );
INSERT INTO VEHICULO (DESCRIPCION,MARCA,MODELO,COLOR,MATRICULA,ANIO) VALUES ('Tractor Nuevo','Fiat' ,'R123','Amarillo','N06-ADA', 1993 );
INSERT INTO REVOLVENTE (DESCRIPCION,ES_INGRESO,MONTO,OBRA_ID,VEHICULO_ID) VALUES('Adelando Obras Mazaryk',1,1276.98,'2','1');
INSERT INTO RENTA (EMPLEADO_ID,DESCRIPCION,FECHA_INICIO,FECHA_FINAL) VALUES(3,'Renta Octubre','2019-10-10','2019-10-16');

